### PR TITLE
Unit Tests initial commit

### PR DESCRIPTION
**Pull request by bethoma**
Updated to WRA Unit tests so that they don't need to use a plugged in Arduino (they use a MockStream/MockBoard) and added some more HardwareProfile and DigitalPin tests (Analog one stubbed out for now).

### CODE REVIEW

**Comment by turkycat** [comment]
Since this was built on top of my upcoming release to remote-wiring, this PR should really be delayed until the develop branch has been updated with my merge.

**Comment by turkycat** [comment]
@HerrickSpencerMSFT comment on your experience per our convo earlier?

**Comment by HerrickSpencerMSFT** [comment]
Code functions nicely, will be good to have for regression testing. However, I agree, we should wait for main changes to underlying RemoteArduino code is in before merging in Unit tests.

**Comment by bethoma** [comment]
This PR has been replaced with: https://github.com/ms-iot/remote-wiring/pull/87
Abandoning.

**Pull request closed without merging**
