### PR TITLE
Split out `Microsoft.Maker.Serial` into its own repository

### PR DESCRIPTION
**Pull request by zfields**
... and included it via git submodule

Created new repository `https://github.com/ms-iot/serial-wiring` to house `Microsoft.Maker.Serial` component

### CODE REVIEW

**Comment by zfields** [comment]
@turkycat Please review and test these changes.

**Comment by turkycat** [comment]
I'm not sure this is the best time to extract this stuff, as I have outstanding changes on my fork which haven't been merged back into ms-iot\master yet

**Comment by zfields** [comment]
How many are we talking, and are you working on Serial? If not, then you can rebase without much, if any, impact. We need this for the VirtualShields work,

**Comment by sidwarkd** [comment]
👍 Cloned the repo and then ran the git submodule commands to bring in the files. I then verified that I could build the project in Debug and Release mode for all 3 targets. Should we modify the README to mention the submodule with instructions on how to pull it in?

**Comment by turkycat** [comment]
:gem:

**Pull request merged**
