### PR TITLE
remove double add of _analog_offset in RemoteDevice::analogRead(Platf…

### PR DESCRIPTION
**Pull request by ManniAT**
As suggested by zfields I fixed this

### CODE REVIEW

**Comment by zfields** [comment]
Looks great ManniAT! We are in the process of review and we should have you pulled in as a HOTFIX asap! Thanks!

**Comment by ManniAT** [comment]
You are welcome zfields,
and it's great to be a contributor on such a great project.
Although it was just a single line of code :)

**Comment by turkycat** [comment]
Hey @ManniAT, we've reviewed your changes and want to thank you for your contribution :)

This whole conversion thing is a hassle to deal with, as you have seen first hand. We added the analogRead( string ) overload explicitly to try to 'hide' this conversion from the user (you!). Therefore, it was a mistake to have the conversion take place twice, so I'm super glad you identified the bug and submitted a fix.

Upon further discussion, we've decided that while it makes sense to have two functions for pinMode() and getPinMode() (one accepting a raw pin number, one accepting a string) the context of analogRead() implies that it should always be an analog pin, and therefore we should only have one version of the function, analogRead( string ). We'd like to change the library in this way, which will also solve the double-conversion issue you identified. 
Since you've identified this bug, and already submitted a contribution, I'd like to ask if you are comfortable and willing to make this change yourself, or if you would prefer us to do it? Thanks again for your dilligence!

**Comment by zfields** [comment]
This looks great!

**Comment by turkycat** [comment]
I second. Tested good in Windows 10. Nice work!

**Comment by ManniAT** [comment]
Thank you Jesse

Von meinem Windows Phone gesendet
________________________________
Von: Jesse Frush<mailto:notifications@github.com>
Gesendet: ‎18.‎08.‎2015 00:57
An: ms-iot/remote-wiring<mailto:remote-wiring@noreply.github.com>
Cc: Manfred Pohler<mailto:manniat@live.com>
Betreff: Re: [remote-wiring] remove double add of _analog_offset in RemoteDevice::analogRead(Platf… (#47)

I second. Tested good in Windows 10. Nice work!

---

**Pull request merged**
